## yanei
## by miaohf @20220610
version: '2.0'
services:

  proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/nginx/html:/var/www/html
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
